# Домашнее задание к лекции " Библиотеки Numpy и scipy"

## Задание 1
### Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10

x = np.arange(0, N)[::-1]

In [3]:
print(type(x))
print(x)

<class 'numpy.ndarray'>
[9 8 7 6 5 4 3 2 1 0]


## Задание 2
### Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
N = 10

_m = np.diag(np.arange(0, N)[::-1])
_m

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
sum_m = 0
_el = 0

for a in _m:
    sum_m += a[_el]
    _el += 1
print(sum_m)

45


## Задание 3
### Решите систему уравнений:
### 4x + 2y + z = 4
### x + 3y = 12
### 5y + 4z = -3

In [6]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [7]:
# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [8]:
# решение

from numpy import linalg as lg

In [9]:
lg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [10]:
# проверка верности

np.allclose( np.dot(a, lg.solve(a, b)), b )

True